#pragma once

enum HlResult {
    HL_SUCCESS = 0,
    HL_FAILURE,
    HL_NO_PHYSICAL_DEVICE,
    HL_DEVICE_COMPATIBILITY_FAILED,
    
    HL_VK_INSTANCE_CREATION_FAILED,
    HL_VK_SURFACE_CREATION_FAILED,
    HL_VK_LOGICAL_DEVICE_CREATION_FAILED,
    HL_VK_SWAPCHAIN_CREATION_FAILED,
    HL_VK_RENDER_PASS_CREATION_FAILED,
    HL_VK_IMAGE_VIEW_CREATION_FAILED,
    HL_VK_SYNC_OBJECT_CREATION_FAILED,
    HL_VK_QUEUE_FAMILY_NOT_FOUND,
    HL_VK_DEBUG_CALLBACK_FAILED
};
